### ISSUE TITLE
Repo is out of date!

### ISSUE THREAD

**Issue by wulftone** [hhvm/hhvm-docker#10]
There have been a few new releases and the images available on docker hub are updated, but this repo is not.

**Comment by mofarrell** [comment]
Does this cause issues for you?  Our new approach does not use this repo to update the docker images

**Comment by wulftone** [comment]
Ah, well I was hoping to look at the Dockerfiles used to create these new images, since they seem to have changed dramatically since 3.18.2 (missing tzdata and a bunch of other things I relied on)--and the docker hub documentation points to this repo.  Where should I go?

**Comment by fredemmott** [comment]
what're the other things? tzdata is a change between upstream ubuntu 14.04 and 16.04 and is being added as an explicit HHVM dependency - maybe the other things need to have that happen too

**Comment by wulftone** [comment]
I am not sure it is something you'd like to include, but I had to also add the `net-tools` package.

**Comment by mofarrell** [comment]
What was broken without `net-tools`?

**Comment by wulftone** [comment]
We were using netstat for something unrelated to hhvm operation

**Comment by mofarrell** [comment]
Cool.
The docker ubuntu 16.04 image is bare bones compared to the 14.04 one.  So 3.19 hhvm images won't extra things by default.  Of course it should have tzdata.
