### ISSUE TITLE
No 3.17 image

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hhvm-docker#6]
https://hub.docker.com/r/hhvm/hhvm/tags/

**Comment by fredemmott** [comment]
refs hhvm/packaging#147
Also need the various LTS and -proxygen images per readme.

**Comment by fredemmott** [comment]
@mofarrell : still missing -proxygen

**Comment by aorenste** [comment]
@fredemmott I was actually in the process of scripting this and was kind of surprised when the script reported that it no longer needed to build hhvm/hhvm:3.17.0 (because @mofarrell built it).  Should be all set now.

**Comment by fredemmott** [comment]
@aorenste : I see it on dockerhub now, but I don't see the proxygen dockerfile change in this repo?

**Comment by fredemmott** [comment]
oh, it was changed to :latest in the previous update; will need care for LTS update though
