### ISSUE TITLE
ubuntu 16.0 lts compatibility

### ISSUE THREAD

**Issue by ghost** [hhvm/hhvm-docker#7]
does this supports ubuntu 16.0 lts distro?

**Comment by fredemmott** [comment]
This is currently based on 14.04 - the container will run on a 16.04 host, and there are also apt packages for 16.04.

**Comment by mofarrell** [comment]
I might add that we will most likely migrate the docker image to 16.04 soon.  As fredemmott said it will run on a 16.04 host regardless, and we also have native package available.  See the docs for all the installation methods: https://docs.hhvm.com/hhvm/installation/introduction

**Comment by fredemmott** [comment]
Just checking: the plan is to keep existing supported HHVM versions on 14.04, and just use 16.04 for HHVM 3.$NEXT+, right?

**Comment by mofarrell** [comment]
I guess I hadn't thought about it, but that would make the most sense.  The reason to switch is so we can stop supporting gcc-4.8 with future releases.

**Comment by fredemmott** [comment]
My concern is that upgrading from HHVM 3.15.x to HHVM 3.15.(x+1) shouldn't upgrade my ubuntu version too :)

**Comment by aorenste** [comment]
@fredemmott Correct - the intent is that at some point (3.18?) we'll switch docker to a new ubuntu version but the existing branches will continue to use ubuntu-14.04
